version: '3'
services:
  web:
    container_name: got_api_web_1
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
  php:
    container_name: got_api_php_1
    image: php:8.0-fpm
    build:
      context: ./docker/php
    volumes:
      - ./app:/app
  mysql:
    container_name: got_api_mysql_1
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./.mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: got
    command:
      mysqld --sql_mode=""
  elasticsearch:
    container_name: got_api_elastic_1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    environment:
      - node.name=got_api_elastic_1
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=got_api_elastic_1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./.elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
